In [10]:

import pandas as pd
import numpy as np


#criar df e colunas, reorganizar  para os rings estarem em ordem crescente

df = pd.read_csv(r'C:\Users\nikit\OneDrive\Desktop\Psn\bayseanos\49541_data.csv',header=None)
df1=df

#mudar o index
df1.columns = df.iloc[0]

df1 = df.reindex(df1.index.drop(0)).reset_index(drop=True)

df1.columns.name = None
df1

#df1.head(10)

        Doenca Fumo Falta de força Dificuldade em pegar
0      Pistons    1              1                    0
1     Eletrico    0              0                    1
2      Pistons    1              1                    1
3      Pistons    0              1                    0
4      Pistons    1              0                    0
..         ...  ...            ...                  ...
304   Eletrico    0              0                    1
305   Eletrico    0              0                    1
306  Injetores    0              0                    0
307   Eletrico    0              1                    1
308   Eletrico    0              0                    1

[309 rows x 4 columns]

In [11]:
#mudar os nomes para numeros
df1.replace(['Injetores','Pistons','Eletrico'],[1,2,3],inplace=True)
#df1=df1.replace(['Injetores','Pistons','Eletrico'],[1,2,3])
df1

     Doenca Fumo Falta de força Dificuldade em pegar
0         2    1              1                    0
1         3    0              0                    1
2         2    1              1                    1
3         2    0              1                    0
4         2    1              0                    0
..      ...  ...            ...                  ...
304       3    0              0                    1
305       3    0              0                    1
306       1    0              0                    0
307       3    0              1                    1
308       3    0              0                    1

[309 rows x 4 columns]

In [12]:
#calculo de probabilidades 

#converter dataframe toda para inteiros
df1=df1.astype(str).astype(int)

#probabilidade de doenca
P_D=[]

#probabilidade de fumo sabendo que doenca
F_D=[]

#probabilidade de falta de força sabendo que doenca
Ff_D=[]

#probabilidade de dificuldade em pegar sabendo que doenca
Dp_D=[]



#cria lista de doencas exitentes
Doencas=df1["Doenca"].unique().tolist()

Doencas.sort()

#conta os casos existentes
n_casos=np.count_nonzero(df1['Doenca'])

# preenche as listas com as respectivas probabilidades
for v in Doencas:
    P_D.append((np.count_nonzero(df1['Doenca']==v))/n_casos)
    F_D.append(np.count_nonzero((df1['Doenca']==v) & (df1["Fumo"] == 1))/(np.count_nonzero(df1['Doenca']==v)))
    Ff_D.append(np.count_nonzero((df1['Doenca']==v) & (df1["Falta de força"] == 1))/(np.count_nonzero(df1['Doenca']==v)))
    Dp_D.append(np.count_nonzero((df1['Doenca']==v) & (df1["Dificuldade em pegar"] == 1))/(np.count_nonzero(df1['Doenca']==v)))


    
    
#criar dataframe de probabilidades com as listas anteriores

Avaria=['Injetores','Pistons','Electrico']

Tp = pd.DataFrame(list(zip(Avaria,P_D, F_D,Ff_D,Dp_D)),
               columns =["Avaria","P problema", "P fumo |problema","P Falta de força|Problema)","P Dificuldade em pegar|Problema"])



Tp.set_index('Avaria', inplace=True)
Tp

,P problema,P fumo |problema,P Falta de força|Problema),P Dificuldade em pegar|Problema
Avaria,,,,
Injetores,0.229773,0.802817,0.323944,0.394366
Pistons,0.404531,0.624000,0.928000,0.168000
Electrico,0.365696,0.194690,0.123894,0.778761

In [13]:
#camada 3 ->dificuldade em pegar

def prob_avaria_3(F,Ff,Dp):
    list_prob3=[]
    

    #versao 2 das listas de probabilidades
    F_D_2=F_D
    Ff_D_2=Ff_D
    Dp_D_2=Dp_D
    
    if F==0:
         F_D_2=[1-a for a in F_D]
    
    if Ff==0:
         Ff_D_2=[1-a for a in Ff_D]
    
    
    if Dp==0:
         Dp_D_2=[1-a for a in Dp_D]
    
    
    
    list_prob3 = [a*b*c*d for a,b,c,d in zip(P_D,F_D_2,Ff_D_2,Dp_D_2)]
    soma=sum(list_prob3)
    list_prob3 = [a/soma for a in list_prob3]
    
    
    return list_prob3

In [14]:
#camada 2->falta de força

def prob_avaria_2(F,Ff):
    list_prob2=[]
    

    #versao 2 das listas de probabilidades
    F_D_2=F_D
    Ff_D_2=Ff_D
    
    if F==0:
         F_D_2=[1-a for a in F_D]
    
    if Ff==0:
         Ff_D_2=[1-a for a in Ff_D]
    
    
    list_prob2 = [a*b*c for a,b,c in zip(P_D,F_D_2,Ff_D_2)]
    soma=sum(list_prob2)
    list_prob2 = [a/soma for a in list_prob2]
    
    
    return list_prob2

In [15]:
#camada 1->fumo

def prob_avaria_1(F):
    list_prob1=[]
    

    #versao 2 das listas de probabilidades
    F_D_2=F_D
 
    if F==0:
         F_D_2=[1-a for a in F_D]
    
    
    list_prob1 = [a*b for a,b in zip(P_D,F_D_2)]
    soma=sum(list_prob1)
    list_prob1 = [a/soma for a in list_prob1]
    
    
    return list_prob1

In [43]:
#fazer arvore

# from itertools import combinations_with_replacement 
  
# comb = combinations_with_replacement([1, 0, 1], 3) 
# comb = list(dict.fromkeys(comb))
    
    
    
# comb

[(1, 1, 1), (1, 1, 0), (1, 0, 0), (1, 0, 1), (0, 0, 0), (0, 0, 1), (0, 1, 1)]